// Fonts to probe - mix of common, platform-specific, and uncommon discriminators
export const FONT_LIST = [
  // Windows common
  "Arial",
  "Arial Black",
  "Calibri",
  "Cambria",
  "Cambria Math",
  "Comic Sans MS",
  "Consolas",
  "Courier New",
  "Georgia",
  "Impact",
  "Lucida Console",
  "Lucida Sans Unicode",
  "Microsoft Sans Serif",
  "Palatino Linotype",
  "Segoe UI",
  "Segoe UI Emoji",
  "Segoe UI Symbol",
  "Tahoma",
  "Times New Roman",
  "Trebuchet MS",
  "Verdana",
  "Wingdings",
  // macOS common
  "American Typewriter",
  "Apple Color Emoji",
  "Avenir",
  "Avenir Next",
  "Baskerville",
  "Futura",
  "Geneva",
  "Gill Sans",
  "Helvetica",
  "Helvetica Neue",
  "Hoefler Text",
  "Lucida Grande",
  "Menlo",
  "Monaco",
  "Optima",
  "Palatino",
  "San Francisco",
  "SF Pro",
  "SF Mono",
  // Linux common
  "Cantarell",
  "DejaVu Sans",
  "DejaVu Sans Mono",
  "DejaVu Serif",
  "Droid Sans",
  "Droid Sans Mono",
  "FreeMono",
  "Liberation Mono",
  "Liberation Sans",
  "Liberation Serif",
  "Noto Sans",
  "Noto Serif",
  "Ubuntu",
  "Ubuntu Mono",
  // Uncommon discriminators
  "Abadi MT Condensed Light",
  "Bookman Old Style",
  "Century Gothic",
  "Copperplate",
  "Franklin Gothic Medium",
  "Garamond",
  "Papyrus",
  "Rockwell",
  "Brush Script MT",
  "Century Schoolbook",
];
